# Generated by Django 5.0.4 on 2024-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHYS-301', 'PHYS-301'), ('PHYS-302', 'PHYS-302'), ('PHYS-303', 'PHYS-303'), ('PHYS-304', 'PHYS-304'), ('PHYS-305', 'PHYS-305'), ('PHYS-306', 'PHYS-306'), ('PHYS-307', 'PHYS-307')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('session', models.CharField(max_length=20)),
                ('bank_payment_status', models.CharField(choices=[('yes', 'Yes'), ('not_yet', 'Not Yet')], max_length=10)),
                ('bank_slip_serial_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('student_status', models.CharField(choices=[('regular', 'Regular'), ('improvement', 'Improvement')], max_length=12)),
                ('courses', models.ManyToManyField(to='exam_registration.course')),
            ],
        ),
    ]
